version: '3.1'
services:   
   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - db 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db