version: '3.1'
services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    ports:
      - "3000:3000"