version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports: "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  backend:
    image:   # Replace with your image name
    container_name: backend
    ports: "5000:5000"
    depends_on: postgres

  frontend:
    image:   # Replace with your image name
    container_name: frontend
    ports: "3000:3000"
    depends_on: backend