version: '3'
services:   
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    restart: always
    container_name: application
    ports:
      - "8000:8000"
    depends_on:
      - postgres

