version: '3.1'
services:   
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: back
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    container_name: front
    ports:
      - "8100:8100"
    depends_on:
      - back