version: '3.1'
services:   
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - db

